name: IAC Pipeline Vultr VPS Resources Matrix

on:
  push:
    paths:
      - 'iac-template/terraform-hcl-standard/vultr-vps/modules/compute/**'
      - 'iac-template/terraform-hcl-standard/vultr-vps/modules/storage/**'
      - 'iac-template/terraform-hcl-standard/vultr-vps/modules/data_store/**'
      - 'iac-template/terraform-hcl-standard/vultr-vps/envs/dev/**'
      - '.github/workflows/terraform-standard-iac-pipeline-vultr-resources-matrix.yaml'
  workflow_dispatch:
    inputs:
      dry_run:
        type: choice
        options: ['true', 'false']
        default: 'true'

env:
  BASE_DIR: iac-template/terraform-hcl-standard/vultr-vps/envs
  DRY_RUN: ${{ github.event.inputs.dry_run || 'true' }}

jobs:
  terraform:
    name: "${{ matrix.env }} :: pipeline (dry_run=${{ inputs.dry_run }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.51.0

      - name: Export Vultr credentials
        run: echo "TF_VAR_vultr_api_key=${{ secrets.VULTR_API_KEY }}" >> "$GITHUB_ENV"

      - name: Init
        run: terraform -chdir=${{ env.BASE_DIR }}/${{ matrix.env }} init -upgrade

      - name: Plan
        run: terraform -chdir=${{ env.BASE_DIR }}/${{ matrix.env }} plan

      - name: Apply
        if: ${{ env.DRY_RUN == 'false' }}
        run: terraform -chdir=${{ env.BASE_DIR }}/${{ matrix.env }} apply -auto-approve

      - name: Skip Apply (dry-run)
        if: ${{ env.DRY_RUN == 'true' }}
        run: echo "Dry run enabled â†’ skip apply step."

      - name: Output
        if: ${{ env.DRY_RUN == 'false' }}
        run: terraform -chdir=${{ env.BASE_DIR }}/${{ matrix.env }} output -json
